name: Perfrom Type and Formatting checks on a/an new/edited pull request.

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

jobs:
  perfrom-type-and-formatting-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node Modules
        run: npm install

      - name: Run Linting script on src
        run: npm run lint
